// Table `location` Judilibre → nom de juridiction. Port fidèle de
// `_LOCATION_TO_JURISDICTION_NAME` (judilibre.py).
// Inclus dans `extract/judilibre.rs`.

fn location_table() -> &'static [(&'static str, &'static str)] {
    &[
        // Cours d'appel
        ("ca_aix_provence", "Cour d'appel d'Aix-en-Provence"),
        ("ca_amiens", "Cour d'appel d'Amiens"),
        ("ca_angers", "Cour d'appel d'Angers"),
        ("ca_basse_terre", "Cour d'appel de Basse-Terre"),
        ("ca_bastia", "Cour d'appel de Bastia"),
        ("ca_besancon", "Cour d'appel de Besançon"),
        ("ca_bordeaux", "Cour d'appel de Bordeaux"),
        ("ca_bourges", "Cour d'appel de Bourges"),
        ("ca_caen", "Cour d'appel de Caen"),
        ("ca_colmar", "Cour d'appel de Colmar"),
        ("ca_douai", "Cour d'appel de Douai"),
        ("ca_fort_de_france", "Cour d'appel de Fort-de-France"),
        ("ca_grenoble", "Cour d'appel de Grenoble"),
        ("ca_limoges", "Cour d'appel de Limoges"),
        ("ca_lyon", "Cour d'appel de Lyon"),
        ("ca_metz", "Cour d'appel de Metz"),
        ("ca_montpellier", "Cour d'appel de Montpellier"),
        ("ca_nimes", "Cour d'appel de Nîmes"),
        ("ca_noumea", "Cour d'appel de Nouméa"),
        ("ca_orleans", "Cour d'appel d'Orléans"),
        ("ca_papeete", "Cour d'appel de Papeete"),
        ("ca_paris", "Cour d'appel de Paris"),
        ("ca_pau", "Cour d'appel de Pau"),
        ("ca_poitiers", "Cour d'appel de Poitiers"),
        ("ca_reims", "Cour d'appel de Reims"),
        ("ca_rennes", "Cour d'appel de Rennes"),
        ("ca_rouen", "Cour d'appel de Rouen"),
        (
            "ca_st_denis_reunion",
            "Cour d'appel de Saint-Denis de la Réunion",
        ),
        ("ca_toulouse", "Cour d'appel de Toulouse"),
        ("ca_versailles", "Cour d'appel de Versailles"),
        // Tribunaux judiciaires (code INSEE commune)
        ("tj13055", "Tribunal judiciaire de Marseille"),
        ("tj13108", "Tribunal judiciaire de Tarascon"),
        ("tj28085", "Tribunal judiciaire de Chartres"),
        ("tj33063", "Tribunal judiciaire de Bordeaux"),
        ("tj34032", "Tribunal judiciaire de Béziers"),
        ("tj35238", "Tribunal judiciaire de Rennes"),
        ("tj42218", "Tribunal judiciaire de Saint-Étienne"),
        ("tj44109", "Tribunal judiciaire de Nantes"),
        ("tj49007", "Tribunal judiciaire d'Angers"),
        ("tj57672", "Tribunal judiciaire de Thionville"),
        ("tj59350", "Tribunal judiciaire de Lille"),
        ("tj64445", "Tribunal judiciaire d'Oloron-Sainte-Marie"),
        ("tj67482", "Tribunal judiciaire de Strasbourg"),
        ("tj69123", "Tribunal judiciaire de Lyon"),
        ("tj74042", "Tribunal judiciaire de Bonneville"),
        ("tj75056", "Tribunal judiciaire de Paris"),
        ("tj78646", "Tribunal judiciaire de Versailles"),
        ("tj86194", "Tribunal judiciaire de Poitiers"),
        ("tj92050", "Tribunal judiciaire de Nanterre"),
        ("tj93008", "Tribunal judiciaire de Bobigny"),
        ("tj94028", "Tribunal judiciaire de Créteil"),
        (
            "tj97411",
            "Tribunal judiciaire de Saint-Denis de la Réunion",
        ),
        ("tj98735", "Tribunal civil de première instance de Papeete"),
        // Tribunaux de commerce (code département)
        ("0602", "Tribunal de commerce de Cannes"),
        ("0605", "Tribunal de commerce de Nice"),
        ("1101", "Tribunal de commerce de Carcassonne"),
        ("1601", "Tribunal de commerce d'Angoulême"),
        ("2104", "Tribunal de commerce de Dijon"),
        ("2202", "Tribunal de commerce de Saint-Brieuc"),
        ("2801", "Tribunal de commerce de Chartres"),
        ("3102", "Tribunal de commerce de Toulouse"),
        ("3302", "Tribunal de commerce de Bordeaux"),
        ("3303", "Tribunal de commerce de Libourne"),
        ("3405", "Tribunal de commerce de Montpellier"),
        ("3501", "Tribunal de commerce de Rennes"),
        ("3801", "Tribunal de commerce de Grenoble"),
        ("4502", "Tribunal de commerce d'Orléans"),
        ("5601", "Tribunal de commerce de Lorient"),
        ("5910", "Tribunal de commerce de Lille-Métropole"),
        ("6303", "Tribunal de commerce de Clermont-Ferrand"),
        ("7301", "Tribunal de commerce de Chambéry"),
        ("7402", "Tribunal de commerce de Thonon-les-Bains"),
        ("7501", "Tribunal de commerce de Paris"),
        ("7606", "Tribunal de commerce du Havre"),
        ("7801", "Tribunal de commerce d'Évry"),
        ("7802", "Tribunal de commerce de Pontoise"),
        ("8201", "Tribunal de commerce de Montauban"),
        ("8305", "Tribunal de commerce de Toulon"),
        ("8401", "Tribunal de commerce d'Avignon"),
        ("8501", "Tribunal de commerce de La Roche-sur-Yon"),
        ("8602", "Tribunal de commerce de Poitiers"),
        ("9201", "Tribunal de commerce de Nanterre"),
        ("9301", "Tribunal de commerce de Bobigny"),
        // Boucle 2026-06-03
        ("ca_chambery", "Cour d'appel de Chambéry"),
        ("ca_dijon", "Cour d'appel de Dijon"),
        ("tj01053", "Tribunal judiciaire de Bourg-en-Bresse"),
        ("tj30189", "Tribunal judiciaire de Nîmes"),
        ("tj31555", "Tribunal judiciaire de Toulouse"),
        ("tj34172", "Tribunal judiciaire de Montpellier"),
        ("tj54395", "Tribunal judiciaire de Nancy"),
        ("tj77284", "Tribunal judiciaire de Meaux"),
        ("0203", "Tribunal de commerce de Soissons"),
        ("0501", "Tribunal de commerce de Gap"),
        ("0601", "Tribunal de commerce d'Antibes"),
        ("1001", "Tribunal de commerce de Troyes"),
        ("1104", "Tribunal de commerce de Narbonne"),
        ("1301", "Tribunal de commerce d'Aix-en-Provence"),
        ("1303", "Tribunal de commerce de Marseille"),
        ("1708", "Tribunal de commerce de Saintes"),
        ("3201", "Tribunal de commerce d'Auch"),
        ("3601", "Tribunal de commerce de Châteauroux"),
        ("3701", "Tribunal de commerce de Tours"),
        ("3802", "Tribunal de commerce de Vienne"),
        ("4202", "Tribunal de commerce de Saint-Étienne"),
        ("5001", "Tribunal de commerce de Cherbourg"),
        ("5906", "Tribunal de commerce de Valenciennes"),
        ("6002", "Tribunal de commerce de Compiègne"),
        ("7202", "Tribunal de commerce du Mans"),
        ("7608", "Tribunal de commerce de Rouen"),
        ("7701", "Tribunal de commerce de Meaux"),
        ("8102", "Tribunal de commerce de Castres"),
    ]
}
