-- Migration 0078 — Index BM25 sur le corps des articles (ADR 0114, /recherche-textes).
--
-- `legal_article` n'a pas de clé mono-colonne (PK composite
-- `(text_uid, num_key, date_debut)`, migration 0072). ParadeDB exige un
-- `key_field` unique mono-colonne pour l'index BM25 → on ajoute un `id`
-- surrogate (identité), comme `legal_text.id` / `decisions.id`. L'upsert
-- (`ON CONFLICT (text_uid, num_key, date_debut)`) n'y touche pas : nouvelles
-- lignes = nouvel id, lignes mises à jour = id conservé.
--
-- `legal_article_bm25` indexe le corps (`texte`) + le numéro (`num`) ;
-- `source`/`text_uid`/`status` en fast fields (filtre par code, par statut).
-- Mêmes tokenizers que `decisions_bm25` (0053) : regex `[\p{L}\p{N}-]+` +
-- ascii folding + stopwords FR `["a","à"]`, `record: position` (phrases).
-- Lexical seulement (pas de jambe sémantique en v1, ADR 0114).
--
-- ⚠️ `ALTER TABLE ADD COLUMN … IDENTITY` réécrit la table (~3 M lignes,
-- ACCESS EXCLUSIVE) et le build BM25 suit dans la même transaction : à appliquer
-- en fenêtre de maintenance (les pages /loi lisent `legal_article`). Coût disque
-- moindre que `decisions_bm25` (corps d'article ≪ corps de décision).

ALTER TABLE legal_article
    ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX IF NOT EXISTS legal_article_id_key ON legal_article (id);

SET LOCAL maintenance_work_mem = '2GB';
SET LOCAL max_parallel_maintenance_workers = 4;

CREATE INDEX IF NOT EXISTS legal_article_bm25 ON legal_article
USING bm25 (
    id,
    texte,
    num,
    (source::pdb.literal),
    (text_uid::pdb.literal),
    (status::pdb.literal)
)
WITH (
  key_field = 'id',
  text_fields = '{
    "texte": {"tokenizer": {"type": "regex", "pattern": "[\\p{L}\\p{N}-]+", "ascii_folding": true, "stopwords_language": "French", "stopwords": ["a", "à"]}, "record": "position"},
    "num":   {"tokenizer": {"type": "regex", "pattern": "[\\p{L}\\p{N}-]+", "ascii_folding": true, "stopwords_language": "French", "stopwords": ["a", "à"]}, "record": "position"}
  }'
);

ANALYZE legal_article;
