-- Slugs sans uid (ADR 0206).
--
-- 1) Textes étrangers : radical débarrassé des marqueurs pays (gentilé, nom de
--    pays, token alpha-2 historique, préfixe de dataset `jaf-`), identité pays
--    portée par le seul suffixe ISO 3166-1 alpha-3. Table explicite générée
--    depuis l'état de prod du 2026-07-11 et relue ligne à ligne — les
--    abréviations officielles (bgb, ldip, moudawana, coc…) et les composés
--    porteurs de sens (franco-algerienne, syriens-orthodoxes, etat-de-lagos)
--    sont conservés. Zéro collision vérifiée contre tout le catalogue.
WITH renames(text_uid, new_slug) AS (VALUES
  ('jafbase/docAsie/Armenie/CodeCivil.rtf','code-civil-arm'),
  ('jafbase/docAfrique/Angola/filiation angola.pdf','code-famille-filiation-ago'),
  ('jafbase/docAfrique/Angola/mariage.pdf','loi-acte-mariage-11-85-ago'),
  ('jafbase/docAfrique/Angola/divorce.pdf','loi-divorce-9-78-ago'),
  ('translated/code-autrichien-de-procedure-penale','code-de-procedure-penale-aut'),
  ('translated/constitution-autrichienne','constitution-aut'),
  ('belgian/code-civil-belge','code-civil-bel'),
  ('belgian/code-civil-belge-nouveau','code-civil-nouveau-code-civil-bel'),
  ('belgian/code-de-droit-economique','code-de-droit-economique-bel'),
  ('belgian/code-des-societes-belge','code-des-societes-bel'),
  ('belgian/code-instruction-criminelle-belge','code-d-instruction-criminelle-bel'),
  ('belgian/code-judiciaire','code-judiciaire-bel'),
  ('belgian/code-penal-belge','code-penal-bel'),
  ('mjp.univ-perp.fr/be1994','constitution-1994-bel'),
  ('african/code-de-procedure-penale-burkinabe-bf','code-de-procedure-penale-bfa'),
  ('african/code-des-personnes-et-de-la-famille-burkina-bf','code-des-personnes-et-de-la-famille-bfa'),
  ('african/code-procedure-civile-burkinabe-1999-bf','code-procedure-civile-1999-bfa'),
  ('translated/code-penal-bulgare-bg','code-penal-bgr'),
  ('mjp.univ-perp.fr/bg1991','constitution-1991-bgr'),
  ('jafbase/docAfrique/Burundi/Burundi-Code-civil.pdf','code-civil-bdi'),
  ('african/code-personnes-famille-burundi-bi','code-personnes-famille-bdi'),
  ('african/code-de-la-nationalite-beninoise-bj','code-de-la-nationalite-ben'),
  ('jafbase/docAfrique/Benin/Benin_Family_Code.pdf','code-des-personnes-et-de-la-famille-loi-n-2002-07-ben'),
  ('african/code-procedure-civile-commerciale-sociale-benin-bj','code-procedure-civile-commerciale-sociale-ben'),
  ('african/code-procedure-penale-beninois-2012-15-bj','code-procedure-penale-2012-15-ben'),
  ('african/code-enfant-benin-2015','code-enfant-ben'),
  ('african/loi-2020-34-etat-civil-beninoise-bj','loi-2020-34-etat-civil-ben'),
  ('jafbase/docAfrique/Congos/RDC Congo code famille 1987.pdf','code-de-la-famille-loi-n87-010-du-1er-aout-1987-cod'),
  ('african/code-procedure-civile-congolais-rdc-cd','code-procedure-civile-cod'),
  ('african/code-procedure-penale-congolais-rdc-cd','code-procedure-penale-cod'),
  ('african/loi-nationalite-congolaise-rdc-cd','loi-nationalite-cod'),
  ('jafbase/docAfrique/Centrafrique/code de la famille.pdf','code-de-la-famille-loi-n-97-013-caf'),
  ('jafbase/docAfrique/Centrafrique/Code de procedure civile  Centrafrique.pdf','code-procedure-civile-caf'),
  ('jafbase/docAfrique/Congos/Brazzaville code famille 1984.pdf','code-de-la-famille-loi-n073-84-du-17-octobre-1984-cog'),
  ('african/code-de-la-nationalite-congolaise-cg','code-de-la-nationalite-cog'),
  ('african/code-procedure-civile-commerciale-administrative-financiere-congo-cg','code-procedure-civile-commerciale-administrative-financiere-cog'),
  ('african/code-procedure-penale-congolais-brazzaville-cg','code-procedure-penale-cog'),
  ('fedlex/eli/cc/24/233_245_233','code-civil-che'),
  ('fedlex/eli/cc/27/317_321_377','code-des-obligations-che'),
  ('fedlex/eli/cc/1999/404','constitution-federale-che'),
  ('fedlex/eli/cc/1988/1776_1776_1776','loi-droit-international-prive-ldip-che'),
  ('fedlex/eli/cc/2002/510','loi-partie-generale-assurances-sociales-lpga-che'),
  ('fedlex/eli/cc/11/529_488_529','loi-poursuite-dettes-faillite-lp-che'),
  ('african/code-civil-ci-biens','code-civil-biens-civ'),
  ('african/code-civil-ci-contrats-speciaux','code-civil-contrats-speciaux-civ'),
  ('african/code-civil-ci-majeurs-proteges','code-civil-majeurs-proteges-civ'),
  ('african/code-civil-ci-obligations','code-civil-obligations-civ'),
  ('african/code-civil-ci-suretes-prescription','code-civil-suretes-prescription-civ'),
  ('african/code-de-la-nationalite-ivoirienne-ci','code-de-la-nationalite-civ'),
  ('african/code-procedure-civile-commerciale-administrative-ci','code-procedure-civile-commerciale-administrative-civ'),
  ('african/code-procedure-penale-ivoirien-2018-975-ci','code-procedure-penale-2018-975-civ'),
  ('african/loi-2018-862-etat-civil-ci','loi-2018-862-etat-civil-civ'),
  ('african/loi-2018-863-declaration-naissance-deces-ci','loi-2018-863-declaration-naissance-deces-civ'),
  ('african/loi-2019-570-mariage-ivoirienne-ci','loi-2019-570-mariage-civ'),
  ('african/loi-2019-571-filiation-ci','loi-2019-571-filiation-civ'),
  ('african/loi-2020-490-nom-ci','loi-2020-490-nom-civ'),
  ('african/loi-adoption-ci','loi-adoption-civ'),
  ('jafbase/docAfrique/CotedIvoire/Loi_ivoirienne_du_26juin2019_relative_à_la_minorité.pdf','loi-n-2019-572-du-26-juin-2019-relative-a-la-minorite-civ'),
  ('jafbase/docAfrique/CotedIvoire/Cote-dIvoire-état civil.pdf','loi-n-64-374-du-7-octobre-1964-relative-a-l-etat-civil-civ'),
  ('african/loi-paternite-filiation-ivoirienne-64-377-ci','loi-paternite-filiation-64-377-civ'),
  ('jafbase/docAfrique/Cameroun/CODE-CIVIL-CAMEROUNAIS complet.pdf','code-civil-cmr'),
  ('african/code-de-la-nationalite-camerounaise-cm','code-de-la-nationalite-cmr'),
  ('african/code-de-procedure-penale-camerounais-cm','code-de-procedure-penale-cmr'),
  ('faolex.fao.org/CMR-code-travail-92-007','code-du-travail-cmr'),
  ('african/code-penal-camerounais-cm','code-penal-cmr'),
  ('african/code-procedure-civile-commerciale-camerounais-cm','code-procedure-civile-commerciale-cmr'),
  ('cvuc-uccc.com/CMR-ordonnance-81-02-etat-civil','ordonnance-81-02-etat-civil-cmr'),
  ('gesetze-im-internet.de/bgb','code-civil-bgb-deu'),
  ('gesetze-im-internet.de/hgb','code-commerce-hgb-deu'),
  ('gesetze-im-internet.de/stgb','code-penal-stgb-deu'),
  ('gesetze-im-internet.de/gg','loi-fondamentale-gg-deu'),
  ('jafbase/docAfrique/Djibouti/CodeFamille.pdf','code-de-la-famille-dji'),
  ('african/code-de-la-nationalite-djiboutienne-dj','code-de-la-nationalite-dji'),
  ('jafbase/docAfrique/Djibouti/Code de procedure civile 2018 DJIBOUTI.pdf','code-procedure-civile-2018-dji'),
  ('african/code-civil-djibouti-2018','code-civil-dji'),
  ('jafbase/DocAmeriques/Dominicaine/LoiDivorce.pdf','loi-divorce-1306-dom'),
  ('clr.africanchildforum.org/DZA-code-civil-75-58','code-civil-dza'),
  ('jafbase/docMaghreb/Algeriecode_famille.pdf','code-de-la-famille-dza'),
  ('african/code-de-la-nationalite-algerienne-dz','code-de-la-nationalite-dza'),
  ('who.int/cpcd/DZA-ordonnance-70-20-etat-civil','code-de-l-etat-civil-dza'),
  ('jafbase/docMaghreb/algerie code procedure.pdf','code-de-procedure-civile-et-administrative-dza'),
  ('policehumanrightsresources.org/DZA-code-penal-1966','code-penal-1966-dza'),
  ('jafbase/docMaghreb/AlgerieConvEnfantsMixtes.pdf','convention-franco-algerienne-enfants-couples-mixtes-1988-dza'),
  ('foreign/code-civil-egyptien-eg','code-civil-egy'),
  ('foreign/code-commerce-egyptien-eg','code-commerce-egy'),
  ('foreign/code-penal-egyptien-eg','code-penal-egy'),
  ('foreign/code-procedure-penale-egyptien-eg','code-procedure-penale-egy'),
  ('jafbase/docAfrique/Egypte/traduction loi 100 de 1985.pdf','loi-100-1985-statut-personnel-egy'),
  ('jafbase/docAfrique/Egypte/traduction loi 44 de 1979 remplacée par la loi 100 de 1985.pdf','loi-44-1979-statut-personnel-egy'),
  ('jafbase/docAfrique/Egypte/traduction lois de 1920 et 1929.pdf','lois-statut-personnel-1920-1929-egy'),
  ('boe.es/codigo-civil','code-civil-esp'),
  ('translated/code-de-procedure-civile-espagnol-es','code-de-procedure-civile-esp'),
  ('translated/code-penal-espagnol-es','code-penal-esp'),
  ('mjp.univ-perp.fr/es1978','constitution-1978-esp'),
  ('faolex.fao.org/GAB-code-civil-15-72-p1','code-civil-loi-15-72-p1-gab'),
  ('faolex.fao.org/GAB-code-civil-p2-1989','code-civil-p2-successions-gab'),
  ('african/code-de-la-nationalite-gabonaise-ga','code-de-la-nationalite-gab'),
  ('african/code-de-procedure-civile-gabonais-ga','code-de-procedure-civile-gab'),
  ('african/code-procedure-penale-gabonais-ga','code-procedure-penale-gab'),
  ('jafbase/docAfrique/Guinee/Code-civil-de-2019.pdf','code-civil-gin'),
  ('african/code-de-l-enfant-guineen-gn','code-de-l-enfant-gin'),
  ('a-mla.org/GIN-CPCEA-1998-D98-100','code-de-procedure-civile-economique-et-administrative-gin'),
  ('african/code-procedure-penale-guineen-2016-gn','code-procedure-penale-2016-gin'),
  ('translated/code-civil-grec-gr','code-civil-grc'),
  ('translated/code-des-douanes-grec','code-des-douanes-grc'),
  ('mjp.univ-perp.fr/gr2019','constitution-2019-grc'),
  ('foreign/code-civil-haitien-ht','code-civil-hti'),
  ('jafbase/DocAmeriques/Haiti/loi-sur-la-paternite-et-la-filiation- 2014 pdf.pdf','loi-paternite-maternite-filiation-hti'),
  ('jafbase/DocAmeriques/Haiti/loi-reformant-l-adoption-en-haiti_haitijustice.pdf','loi-reformant-l-adoption-hti'),
  ('translated/code-civil-hongrois-hu','code-civil-hun'),
  ('translated/code-de-procedure-penale-hongrois','code-de-procedure-penale-hun'),
  ('translated/code-du-travail-hongrois','code-du-travail-hun'),
  ('jafbase/docAsie/Irak/code civil irakien 1951.pdf','code-civil-1951-irq'),
  ('brocardi.it/codice-civile','code-civil-ita'),
  ('translated/code-de-procedure-penale-italien-it','code-de-procedure-penale-ita'),
  ('brocardi.it/codice-penale','code-penal-ita'),
  ('brocardi.it/codice-di-procedura-civile','code-procedure-civile-ita'),
  ('cdpc.univ-tln.fr/constit_italie_2022','constitution-1947-ita'),
  ('jafbase/docUE/Italie/LoiDIP.pdf','loi-dip-218-1995-ita'),
  ('jafbase/docAsie/Jordanie/code civil jordanien 1976.pdf','code-civil-1976-jor'),
  ('jafbase/docAfrique/Comores/code de la famille comorien.pdf','code-de-la-famille-com'),
  ('african/code-de-la-nationalite-comorienne-km','code-de-la-nationalite-com'),
  ('african/code-de-l-etat-civil-comorien-km','code-de-l-etat-civil-com'),
  ('clr.africanchildforum.org/COM-loi-84-10-etat-civil','loi-84-10-etat-civil-com'),
  ('foreign/code-obligations-contrats-libanais-lb','code-obligations-contrats-lbn'),
  ('jafbase/docAsie/Liban/non musulmans textes.pdf','loi-sur-le-statut-personnel-successions-des-non-musulmans-lbn'),
  ('jafbase/docAsie/Liban/lois communes.PDF','lois-etat-civil-communes-lbn'),
  ('legilux/eli/etat/leg/code/civil','code-civil-lux'),
  ('jafbase/docMaghreb/MarocCodeFam-oct2005.pdf','code-de-la-famille-moudawana-2004-mar'),
  ('african/code-de-la-nationalite-marocaine-ma','code-de-la-nationalite-mar'),
  ('african/code-de-l-etat-civil-marocain-ma','code-de-l-etat-civil-mar'),
  ('african/code-de-procedure-civile-marocain-ma','code-de-procedure-civile-mar'),
  ('african/code-de-procedure-penale-marocain-ma','code-de-procedure-penale-mar'),
  ('casainvest.ma/MA-code-travail-65-99-BO5210','code-du-travail-loi-65-99-mar'),
  ('rabat.eregulations.org/MAR-DOC-1913','code-obligations-contrats-doc-mar'),
  ('onousc.ma/MA-code-penal-1962-consolide-2018','code-penal-1962-mar'),
  ('african/loi-kafala-marocaine-15-01-ma','loi-kafala-15-01-mar'),
  ('monaco/loi-1448-2017-dip','loi-1448-2017-dip-mco'),
  ('african/code-de-l-etat-civil-malgache-mg','code-de-l-etat-civil-mdg'),
  ('botschaft-madagaskar.de/MDG-code-nationalite-60-064','code-nationalite-mdg'),
  ('jafbase/docAfrique/Madagascar/Adoption - loi d''application Madagascar.pdf','decret-2006-596-application-loi-adoption-mdg'),
  ('cnlegis.gov.mg/L2018-027','loi-2018-027-etat-civil-mdg'),
  ('african/loi-filiation-malgache-mg','loi-filiation-mdg'),
  ('jafbase/docAfrique/Madagascar/Loi sur l''adoption malgache.pdf','loi-n-2005-014-du-7-septembre-2005-relative-a-l-adoption-mdg'),
  ('jafbase/docAfrique/Madagascar/LoiMariage.pdf','loi-n-2007-022-du-20-aout-2007-relative-au-mariage-et-aux-regimes-matrimoniaux-mdg'),
  ('jafbase/docAfrique/Madagascar/Loi droits et protection des enfants Madagascar.pdf','loi-n-2007-023-du-20-aout-2007-sur-les-droits-et-la-protection-des-enfants-mdg'),
  ('jafbase/docAfrique/Madagascar/LoiDIP.pdf','ordonnance-n-62-041-du-19-septembre-1962-relative-aux-dispositions-generales-de-droit-interne-et-de-droit-international-prive-mdg'),
  ('african/code-de-la-nationalite-malienne-ml','code-de-la-nationalite-mli'),
  ('sgg-mali.ml/CPCCS-1999-maj2009','code-de-procedure-civile-commerciale-et-sociale-mli'),
  ('jafbase/docAfrique/Mali/Code_des_Personnes_et_de_la_Famille nouveau.pdf','code-des-personnes-et-de-la-famille-loi-n2011-087-mli'),
  ('african/code-penal-malien-ml','code-penal-mli'),
  ('african/code-procedure-penale-malien-ml','code-procedure-penale-mli'),
  ('african/code-parente-mali-ordonnance-73-036-ml','code-parente-mli'),
  ('african/loi-etat-civil-malienne-06-024-ml','loi-etat-civil-06-024-mli'),
  ('african/loi-etat-civil-malienne-87-27-ml','loi-etat-civil-87-27-mli'),
  ('african/code-de-la-nationalite-mauritanienne-mr','code-de-la-nationalite-mrt'),
  ('african/code-de-l-etat-civil-mauritanien-2011-mr','code-de-l-etat-civil-2011-mrt'),
  ('african/code-de-l-etat-civil-mauritanien-mr','code-de-l-etat-civil-mrt'),
  ('jafbase/docAfrique/Mauritanie/CodeStatutPerso.pdf','code-du-statut-personnel-loi-n-2001-052-mrt'),
  ('jafbase/docAfrique/Maurice/MauriceCodeCivil.pdf','code-civil-mus'),
  ('NC/CODE-IMPOTS','code-impots-ncl'),
  ('african/code-de-la-nationalite-nigerienne-ne','code-de-la-nationalite-ner'),
  ('african/code-de-procedure-civile-niger-ne','code-de-procedure-civile-ner'),
  ('african/code-procedure-penale-nigerien-ne','code-procedure-penale-ner'),
  ('african/loi-2019-29-etat-civil-niger-ne','loi-2019-29-etat-civil-ner'),
  ('jafbase/docAfrique/Nigeria/Loi_LAGOS_NGA_Fr adoption.pdf','loi-sur-adoption-etat-de-lagos-nga'),
  ('translated/code-civil-neerlandais-nl','code-civil-nld'),
  ('translated/code-de-procedure-civile-neerlandais-nl','code-de-procedure-civile-nld'),
  ('translated/code-penal-neerlandais','code-penal-nld'),
  ('translated/constitution-neerlandaise','constitution-nld'),
  ('jafbase/DocAmeriques/Perou/codecivil.PDF','code-civil-per'),
  ('jafbase/DocAmeriques/Perou/LoiDivorceNonContentieux.pdf','loi-divorce-29227-per'),
  ('lexpol.cloud.pf/code-amenagement-pf','code-amenagement-pyf'),
  ('lexpol.cloud.pf/code-impots-pf','code-des-impots-pyf'),
  ('translated/code-civil-polonais-pl','code-civil-pol'),
  ('translated/code-de-la-famille-polonais','code-de-la-famille-pol'),
  ('translated/code-du-travail-polonais-pl','code-du-travail-pol'),
  ('translated/code-penal-polonais','code-penal-pol'),
  ('mjp.univ-perp.fr/pl1997','constitution-1997-pol'),
  ('pgdlisboa.pt/codigo-civil','code-civil-prt'),
  ('translated/code-de-procedure-civile-portugais-pt','code-de-procedure-civile-prt'),
  ('translated/code-de-procedure-penale-portugais','code-de-procedure-penale-prt'),
  ('parlamento.pt/CRP-7e-revision-2005','constitution-1976-prt'),
  ('translated/code-civil-roumain','code-civil-rou'),
  ('translated/code-de-procedure-civile-roumain','code-de-procedure-civile-rou'),
  ('translated/code-penal-roumain','code-penal-rou'),
  ('mjp.univ-perp.fr/ro2003','constitution-2003-rou'),
  ('jafbase/docEstEurope/Serbie/Loi familiale (porodicnizakonfrancuski) non officielle.pdf','loi-familiale-srb'),
  ('zakonrf.info/gk','code-civil-rus'),
  ('translated/code-de-procedure-penale-russe-ru','code-de-procedure-penale-rus'),
  ('mjp.univ-perp.fr/ru1993','constitution-1993-rus'),
  ('foreign/code-penal-rwandais-rw','code-penal-rwa'),
  ('jafbase/docAfrique/Senegal/CODE_FAMILLE sénégal 2018.pdf','code-de-la-famille-sen'),
  ('african/code-de-la-nationalite-senegalaise-sn','code-de-la-nationalite-sen'),
  ('african/code-de-procedure-civile-senegalais-sn','code-de-procedure-civile-sen'),
  ('justice.sec.gouv.sn/code-procedure-penal','code-de-procedure-penale-sen'),
  ('natlex.ilo.org/SEN-code-travail-97-17','code-du-travail-sen'),
  ('african/code-etat-civil-senegalais-sn','code-etat-civil-sen'),
  ('african/code-penal-senegalais-sn','code-penal-sen'),
  ('jafbase/docAfrique/Sao Tome/Loi famille.pdf','code-famille-2-77-stp'),
  ('jafbase/docAsie/Syrie/CodeCivDIP.pdf','code-civil-syr'),
  ('jafbase/docAsie/Syrie/Code civil syrien 1949.pdf','code-civil-1949-syr'),
  ('jafbase/docAsie/Syrie/code du statut personnel des syriens orthodoxes.pdf','code-statut-personnel-syriens-orthodoxes-syr'),
  ('jafbase/docAsie/Syrie/loi sur les sectes religieuses 1936.pdf','loi-communautes-religieuses-60-1936-syr'),
  ('jafbase/docAfrique/Tchad/code civil Tchad 1959.pdf','code-civil-tcd'),
  ('african/code-de-la-nationalite-tchadienne-td','code-de-la-nationalite-tcd'),
  ('jafbase/docAfrique/Tchad/Loi 29 mai 2013 portant code de l''organisation judiciaire.pdf','code-de-lorganisation-judiciaire-tcd'),
  ('african/code-de-procedure-civile-tchadien-td','code-de-procedure-civile-tcd'),
  ('african/code-de-procedure-penale-tchadien-td','code-de-procedure-penale-tcd'),
  ('african/ordonnance-002-pr-2020-etat-civil-tchad-td','ordonnance-002-pr-2020-etat-civil-tcd'),
  ('jafbase/docAfrique/Togo/CodeCiv.pdf','code-civil-tgo'),
  ('african/code-de-la-nationalite-togolaise-tg','code-de-la-nationalite-tgo'),
  ('african/code-des-personnes-et-de-la-famille-togo-tg','code-des-personnes-et-de-la-famille-tgo'),
  ('african/code-procedure-civile-togolais-tg','code-procedure-civile-tgo'),
  ('african/code-procedure-penale-togolais-tg','code-procedure-penale-tgo'),
  ('african/loi-2009-010-etat-civil-togo-tg','loi-2009-010-etat-civil-tgo'),
  ('african/code-de-droit-international-prive-tunisien-tn','code-de-droit-international-prive-tun'),
  ('african/code-de-la-nationalite-tunisienne-tn','code-de-la-nationalite-tun'),
  ('african/code-de-l-etat-civil-tunisien-tn','code-de-l-etat-civil-tun'),
  ('jafbase/docMaghreb/TunisieStatutpersonnel.PDF','code-du-statut-personnel-tun'),
  ('cmf.tn/TN-code-incitations-investissements-93-120','code-incitations-investissements-tun'),
  ('cabinetnfm.com/TUN-COC-1906','code-obligations-contrats-coc-tun'),
  ('african/code-penal-tunisien-tn','code-penal-tun'),
  ('mjp.univ-perp.fr/tn2014','constitution-2014-tun'),
  ('translated/code-civil-turc-tr','code-civil-tur'),
  ('mjp.univ-perp.fr/tr1982','constitution-1982-tur'),
  ('translated/code-de-procedure-penale-ukrainien-ua','code-de-procedure-penale-ukr'),
  ('mjp.univ-perp.fr/ua1996','constitution-1996-ukr'),
  ('translated/constitution-venezuelienne','constitution-ven'),
  ('jafbase/DocAmeriques/Venezuela/LoiDIP.PDF','loi-dip-1998-ven'),
  ('jafbase/docAsie/Vietnam/Code civil vietnam 2015 FR.pdf','code-civil-2015-vnm'),
  ('jafbase/docAsie/Vietnam/DecretEnregistrementMariages.pdf','decret-77-2001-enregistrement-mariage-vnm'),
  ('jafbase/docAsie/Vietnam/LoiFamille.pdf','loi-mariage-famille-2000-vnm')
)
UPDATE legal_text t
SET slug = r.new_slug
FROM renames r
WHERE t.text_uid = r.text_uid;

-- 2) Slugs désambiguïsés par uid (`-cir_NNN`, `-jorftextNNN`, `-legitextNNN`) :
--    remis à NULL, régénérés par la passe `assign-slugs` (cascade sans uid :
--    slug complet → date → NOR → ordinal).
UPDATE legal_text
SET slug = NULL
WHERE slug ~ '-(cir_[0-9]+|jorftext[0-9]+|legitext[0-9]+)$';
